version: '3.8'

services:
  mysql-docker:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
#    volumes:
#      - /data/mysql
    ports:
      - 3307:3306
  my-rest-api:
    image: my-rest-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker
    ports:
      - 8080:8080
#    volumes:
#      - /data/spring-boot-app


networks:
  external-api: